### ISSUE TITLE
Overall Project Tracking

### ISSUE THREAD

**Issue by drguthals** [drguthals/MakeYourMark#1]
Initial Steps: 
- [x] Make a simple HTML to show MakeCode projects - #2 
- [x] Have an HTML file in the docs folder that will automatically deploy as a GitHub page with a merge - #4
- [x] Create deployment branch - https://github.com/drguthals/MakeYourMark/tree/deployment
- [x] Create GitHub pages: http://guthals.com/MakeYourMark/
- [x] Update README - #6 
- [x] Create a list of the MakeCode projects in a file - #8 

Frantic Updates Before Build
- [x] Create a simple text box to enter new MakeCode projects
- [x] Update the universe locally from the text box
- [x] Create CodeTour
- [x] Update README

Next Steps
- [ ] Get index.html to bring URLs from a file
- [ ] Update README
- [ ] Get index.html to arrange simulators dynamically
- [ ] Update README
- [ ] Update the file with the URLs that sent through the form
- [ ] Get the index.html file to update from the new file when something is added
- [ ] Update README

Random Ideas
- [ ] Make each simulator a flip card so when it's clicked on information about that constellation is displayed
